using static Kyrios.Game.AchievementIcons;

namespace Kyrios.Game;

/// <summary>
/// Catálogo de conquistas, na ordem em que aparecem na página (agrupadas por categoria). Pra criar uma nova
/// basta uma linha em <see cref="Handmade"/>: id estável (é o que fica salvo), nome, descrição, categoria,
/// dificuldade, condição (atalhos em <see cref="Unlock"/>) e ícone (<see cref="AchievementIcons"/>) — sem
/// código específico em lugar nenhum. Se a condição precisar de uma estatística que ainda não existe, ela entra
/// no <see cref="SaveData"/> e é atualizada em <see cref="Progression.RecordRace"/>. A conquista secreta de cada
/// pista é gerada a partir de <see cref="TrackThemes"/>, então uma pista nova já vem com a dela.
/// Textos em maiúsculas e sem acento (limite da fonte pixelizada).
/// </summary>
public static class Achievements
{
    // Ids usados como requisito de skins/pistas.
    public const string WhereAreTheBrakesId = "onde_estao_os_freios";
    public const string PredatorId = "predador";
    public const string WasThatSupposedToHappenId = "era_para_isso";

    private const AchievementCategory DeathRace = AchievementCategory.DeathRace;
    private const AchievementCategory TimeAttack = AchievementCategory.TimeAttack;
    private const AchievementCategory Tracks = AchievementCategory.Tracks;
    private const AchievementCategory Skins = AchievementCategory.Skins;
    private const AchievementCategory General = AchievementCategory.General;
    private const AchievementCategory Silly = AchievementCategory.Silly;

    private const Difficulty Easy = Difficulty.Easy;
    private const Difficulty Medium = Difficulty.Medium;
    private const Difficulty Hard = Difficulty.Hard;
    private const Difficulty VeryHard = Difficulty.VeryHard;
    private const Difficulty Rare = Difficulty.Rare;

    private static readonly Achievement[] Handmade =
    [
        // ----- Corrida Mortal -----
        new("sobrevivente", "SOBREVIVENTE", "SOBREVIVA A UMA ELIMINACAO NA CORRIDA MORTAL", DeathRace, Easy,
            Unlock.RoundsSurvived(1), Art(Shield)),
        new("ultimo_de_pe", "ULTIMO DE PE", "VENCA SUA PRIMEIRA CORRIDA MORTAL", DeathRace, Easy,
            Unlock.DeathRaceWins(1), Art(Crown)),
        new("no_podio", "NO PODIO", "TERMINE UMA CORRIDA MORTAL ENTRE OS 3 PRIMEIROS", DeathRace, Easy,
            Unlock.Stat("TERMINE NO TOP 3", p => p.EliminationPodiums, 1), Art(Medal)),
        new("de_virada", "DE VIRADA", "VENCA DEPOIS DE JA TER ESTADO EM ULTIMO LUGAR", DeathRace, Medium,
            Unlock.Stat("VENCA DEPOIS DE ESTAR EM ULTIMO", p => p.EliminationComebackWins, 1), Art(ArrowUp)),
        new("so_pode_sobrar_um", "SO PODE SOBRAR UM", "VENCA SEM FICAR EM ULTIMO NENHUMA VEZ", DeathRace, Medium,
            Unlock.Stat("VENCA SEM NUNCA FICAR EM ULTIMO", p => p.EliminationFlawlessWins, 1), Art(Recolor(Crown, "YC", "Db", "RW"))),
        new("veterano", "VETERANO", "JOGUE 30 CORRIDAS MORTAIS", DeathRace, Medium,
            Unlock.DeathRaces(30), Art(Recolor(Shield, "BR"), "30")),
        new("sobrevivente_nato", "SOBREVIVENTE NATO", "SOBREVIVA A 100 ELIMINACOES NA CORRIDA MORTAL", DeathRace, Medium,
            Unlock.RoundsSurvived(100), Art(Shield, "100")),
        new("estreia_vitoriosa", "ESTREIA VITORIOSA", "VENCA LOGO NA PRIMEIRA PARTIDA COM UMA SKIN", DeathRace, Medium,
            Unlock.Stat("VENCA NA ESTREIA DE UMA SKIN", p => p.FreshSkinWins, 1), Art(Recolor(Star, "YG"))),
        new("frequentador_do_podio", "FREQUENTADOR DO PODIO", "TERMINE 25 CORRIDAS MORTAIS NO TOP 3", DeathRace, Medium,
            Unlock.Stat("25 VEZES NO TOP 3", p => p.EliminationPodiums, 25), Art(Medal, "25")),
        new("em_sequencia", "EM SEQUENCIA", "VENCA 3 CORRIDAS MORTAIS SEGUIDAS", DeathRace, Hard,
            Unlock.DeathRaceWinStreak(3), Art(Fire, "3")),
        new("implacavel", "IMPLACAVEL", "VENCA 10 CORRIDAS MORTAIS", DeathRace, Hard,
            Unlock.DeathRaceWins(10), Art(Crown, "10")),
        new("no_limite", "NO LIMITE", "VENCA DEPOIS DE ESTAR EM ULTIMO COM SO 3 CARROS NA PISTA", DeathRace, Hard,
            Unlock.Stat("VIRADA NOS 3 FINAIS", p => p.EliminationClutchWins, 1), Art(Recolor(ArrowUp, "GR", "gr"))),
        new("foto_de_chegada", "FOTO DE CHEGADA", "VENCA COM O ULTIMO RIVAL CAINDO COLADO EM VOCE", DeathRace, Hard,
            Unlock.Stat("VITORIA APERTADA", p => p.EliminationPhotoFinishWins, 1), Art(Recolor(Flag, "WY"))),
        new("pe_na_tabua", "PE NA TABUA", "VENCA A MORTAL SEM SOLTAR O ACELERADOR", DeathRace, Hard,
            Unlock.Stat("VENCA SEM SOLTAR O ACELERADOR", p => p.EliminationFullThrottleWins, 1), Art(Speedometer, "MAX")),
        new("time_que_ganha", "TIME QUE GANHA NAO SE MEXE", "VENCA 3 MORTAIS SEGUIDAS COM A MESMA SKIN", DeathRace, Hard,
            Unlock.SameSkinWinStreak(3), Art(Recolor(Fire, "RB", "OC"), "3")),
        new("centenario", "CENTENARIO", "JOGUE 100 CORRIDAS MORTAIS", DeathRace, Hard,
            Unlock.DeathRaces(100), Art(Recolor(Shield, "BD"), "100")),
        new(PredatorId, "PREDADOR", "VENCA 25 CORRIDAS MORTAIS", DeathRace, VeryHard,
            Unlock.DeathRaceWins(25), Art(Skull, "25")),
        new("imbativel", "IMBATIVEL", "VENCA 5 CORRIDAS MORTAIS SEGUIDAS", DeathRace, VeryHard,
            Unlock.DeathRaceWinStreak(5), Art(Recolor(Fire, "RP", "OC", "YW"), "5")),
        new("motor_original", "MOTOR ORIGINAL", "VENCA UMA CORRIDA MORTAL SEM USAR O TURBO", DeathRace, VeryHard,
            Unlock.Stat("VENCA SEM TURBO", p => p.EliminationNoBoostWins, 1), Art(Recolor(Turbo, "CL"))),
        new("lataria_intacta", "LATARIA INTACTA", "VENCA UMA CORRIDA MORTAL SEM BATER EM NADA", DeathRace, VeryHard,
            Unlock.Stat("VENCA SEM BATER", p => p.EliminationCleanWins, 1), Art(Recolor(Shield, "BY", "WD"))),
        new("de_ponta_a_ponta", "DE PONTA A PONTA", "VENCA A MORTAL SEM SAIR DO 1º LUGAR NENHUMA VEZ", DeathRace, VeryHard,
            Unlock.Stat("SEMPRE EM 1º", p => p.EliminationWireToWireWins, 1), Art(Recolor(Crown, "YF", "DP"), "1º")),
        new("virada_historica", "VIRADA HISTORICA", "VENCA 5 CORRIDAS MORTAIS DE VIRADA", DeathRace, VeryHard,
            Unlock.Stat("5 VITORIAS DE VIRADA", p => p.EliminationComebackWins, 5), Art(ArrowUp, "5")),
        new("sobrevivente_lendario", "SOBREVIVENTE LENDARIO", "SOBREVIVA A 500 ELIMINACOES NA CORRIDA MORTAL", DeathRace, VeryHard,
            Unlock.RoundsSurvived(500), Art(Recolor(Shield, "BP"), "500")),
        new("lenda_da_mortal", "LENDA DA MORTAL", "VENCA 50 CORRIDAS MORTAIS", DeathRace, Rare,
            Unlock.DeathRaceWins(50), Art(Recolor(Trophy, "YP", "Db"), "50")),
        new("invencivel", "INVENCIVEL", "VENCA 10 CORRIDAS MORTAIS SEGUIDAS", DeathRace, Rare,
            Unlock.DeathRaceWinStreak(10), Art(Recolor(Fire, "RP", "OP", "YW"), "10")),
        new("perfeito", "PERFEITO", "VENCA SEM BATER, SEM TURBO E SEM SAIR DO 1º LUGAR... EM CORRIDAS DIFERENTES", DeathRace, Rare,
            Unlock.All("SEM BATER, SEM TURBO E SEMPRE EM 1º", Unlock.Stat("VENCA SEM BATER", p => p.EliminationCleanWins, 1), Unlock.Stat("VENCA SEM TURBO", p => p.EliminationNoBoostWins, 1), Unlock.Stat("SEMPRE EM 1º", p => p.EliminationWireToWireWins, 1)),
            Art(Recolor(Diamond, "CR", "BP"))),

        // ----- Contra o Relógio -----
        new("contra_o_tempo", "CONTRA O TEMPO", "JOGUE SUA PRIMEIRA PARTIDA DO CONTRA O RELOGIO", TimeAttack, Easy,
            Unlock.TimeAttackRaces(1), Art(Stopwatch)),
        new("aquecimento", "AQUECIMENTO", "FACA 300 PTS NUMA PARTIDA DO RELOGIO", TimeAttack, Easy,
            Unlock.TimeAttackScore(300), Art(Stopwatch, "300")),
        new("recordista", "RECORDISTA", "ESTABELECA SEU PRIMEIRO RECORDE NO RELOGIO", TimeAttack, Easy,
            Unlock.Stat("1 RECORDE PESSOAL", p => p.RecordsSet, 1), Art(Star)),
        new("boa_marca", "BOA MARCA", "FACA 600 PTS NUMA PARTIDA DO RELOGIO", TimeAttack, Medium,
            Unlock.TimeAttackScore(600), Art(Stopwatch, "600")),
        new("cada_segundo_conta", "CADA SEGUNDO CONTA", "FACA 1000 PTS NUMA PARTIDA DO RELOGIO", TimeAttack, Medium,
            Unlock.TimeAttackScore(1000), Art(Stopwatch, "1K")),
        new("sem_tempo_a_perder", "SEM TEMPO A PERDER", "ACUMULE 5000 PTS NO CONTRA O RELOGIO", TimeAttack, Medium,
            Unlock.TimeAttackTotal(5000), Art(Hourglass, "5K")),
        new("nao_consigo_parar", "NAO CONSIGO PARAR", "SUPERE O SEU PROPRIO RECORDE 5 VEZES", TimeAttack, Medium,
            Unlock.Stat("SUPERE SEU RECORDE 5 VEZES", p => p.RecordsBeaten, 5), Art(Star, "5")),
        new("intocavel", "INTOCAVEL", "FACA 500 PTS SEM BATER EM NADA", TimeAttack, Medium,
            Unlock.Stat("500 PTS SEM BATER", p => p.BestCleanTimeAttackScore, 500), Art(Diamond)),
        new("mao_firme", "MAO FIRME", "PASSE POR 12 CHECKPOINTS SEGUIDOS SEM BATER", TimeAttack, Medium,
            Unlock.Stat("12 CHECKPOINTS SEM BATER", p => p.BestCleanCheckpointStreak, 12), Art(Speedometer)),
        new("hora_extra", "HORA EXTRA", "JOGUE 50 VEZES O CONTRA O RELOGIO", TimeAttack, Medium,
            Unlock.TimeAttackRaces(50), Art(Recolor(Hourglass, "YB"), "50")),
        new("na_zona", "NA ZONA", "FACA 1500 PTS NUMA PARTIDA DO RELOGIO", TimeAttack, Hard,
            Unlock.TimeAttackScore(1500), Art(Recolor(Stopwatch, "EO"), "1.5K")),
        new("tempo_de_sobra", "TEMPO DE SOBRA", "TENHA 30 S OU MAIS NO RELOGIO AO MESMO TEMPO", TimeAttack, Hard,
            Unlock.Stat("30 S NO RELOGIO", p => p.MostTimeBanked, 30), Art(Recolor(Hourglass, "YG"))),
        new("maratona", "MARATONA", "COMPLETE 10 VOLTAS NUMA UNICA PARTIDA DO RELOGIO", TimeAttack, Hard,
            Unlock.Stat("10 VOLTAS NUMA PARTIDA", p => p.MostTimeAttackLaps, 10), Art(Flag, "10")),
        new("o_tempo_nao_para", "O TEMPO NAO PARA", "ACUMULE 20000 PTS NO CONTRA O RELOGIO", TimeAttack, Hard,
            Unlock.TimeAttackTotal(20000), Art(Recolor(Hourglass, "YR"), "20K")),
        new("sempre_melhor", "SEMPRE MELHOR", "SUPERE O SEU PROPRIO RECORDE 10 VEZES", TimeAttack, Hard,
            Unlock.Stat("SUPERE SEU RECORDE 10 VEZES", p => p.RecordsBeaten, 10), Art(Recolor(Star, "YC"), "10")),
        new("coracao_na_mao", "CORACAO NA MAO", "PASSE POR 3 CHECKPOINTS COM MENOS DE 1 S NO RELOGIO NUMA PARTIDA", TimeAttack, Hard,
            Unlock.Stat("3 CHECKPOINTS NO ULTIMO SEGUNDO", p => p.MostClutchCheckpointsInRun, 3), Art(Recolor(BrokenHeart, "RP"), "3")),
        new("economico", "ECONOMICO", "FACA 800 PTS NO RELOGIO SEM USAR O TURBO", TimeAttack, Hard,
            Unlock.Stat("800 PTS SEM TURBO", p => p.BestNoBoostTimeAttackScore, 800), Art(Recolor(Turbo, "CG"))),
        new("contra_todos_os_limites", "CONTRA TODOS OS LIMITES", "FACA 2000 PTS NUMA PARTIDA DO RELOGIO", TimeAttack, VeryHard,
            Unlock.TimeAttackScore(2000), Art(Recolor(Stopwatch, "EY", "LD"), "2K")),
        new("perfeicao", "PERFEICAO", "FACA 1000 PTS SEM BATER EM NADA", TimeAttack, VeryHard,
            Unlock.Stat("1000 PTS SEM BATER", p => p.BestCleanTimeAttackScore, 1000), Art(Recolor(Diamond, "CP", "BP", "WF"))),
        new("ultramaratona", "ULTRAMARATONA", "COMPLETE 15 VOLTAS NUMA UNICA PARTIDA DO RELOGIO", TimeAttack, VeryHard,
            Unlock.Stat("15 VOLTAS NUMA PARTIDA", p => p.MostTimeAttackLaps, 15), Art(Recolor(Flag, "WY"), "15")),
        new("cirurgico", "CIRURGICO", "PASSE POR 24 CHECKPOINTS SEGUIDOS SEM BATER", TimeAttack, VeryHard,
            Unlock.Stat("24 CHECKPOINTS SEM BATER", p => p.BestCleanCheckpointStreak, 24), Art(Recolor(Speedometer, "RC"), "24")),
        new("por_um_triz", "POR UM TRIZ", "PASSE NUM CHECKPOINT COM MENOS DE 0.2 S NO RELOGIO", TimeAttack, VeryHard,
            new TimeBelowRequirement("CHECKPOINT COM MENOS DE 0.2 S", p => p.ClosestTimeAttackCall, 0.2f), Art(Recolor(Hourglass, "YR", "DR"), "0.2")),
        new("relojoeiro", "RELOJOEIRO", "ACUMULE 50000 PTS NO CONTRA O RELOGIO", TimeAttack, VeryHard,
            Unlock.TimeAttackTotal(50000), Art(Recolor(Stopwatch, "EP"), "50K")),
        new("lenda_do_relogio", "LENDA DO RELOGIO", "FACA 2500 PTS NUMA PARTIDA DO RELOGIO", TimeAttack, Rare,
            Unlock.TimeAttackScore(2500), Art(Recolor(Trophy, "YC", "DB"), "2.5K")),

        // ----- Pistas -----
        new("primeira_viagem", "PRIMEIRA VIAGEM", "JOGUE EM UMA PISTA DIFERENTE DO AUTODROMO", Tracks, Easy,
            Unlock.TracksPlayed(2), Art(Compass)),
        new("turista", "TURISTA", "JOGUE EM 5 PISTAS DIFERENTES", Tracks, Medium,
            Unlock.TracksPlayed(5), Art(Compass, "5")),
        new("agente_de_viagens", "AGENTE DE VIAGENS", "DESBLOQUEIE 5 PISTAS", Tracks, Medium,
            Unlock.TracksUnlocked(5), Art(Recolor(Compass, "RG", "BY"), "5")),
        new("conquistador", "CONQUISTADOR", "VENCA A CORRIDA MORTAL EM 3 PISTAS DIFERENTES", Tracks, Medium,
            Unlock.TracksWon(3), Art(Recolor(Flag, "WG"), "3")),
        new("explorador", "EXPLORADOR", "ENCONTRE UM SEGREDO ESCONDIDO EM ALGUMA PISTA", Tracks, Medium,
            Unlock.TrackSecretsFound(1), Art(Magnifier)),
        new("rei_da_montanha", "REI DA MONTANHA", "VENCA UMA CORRIDA MORTAL NA MONTANHA", Tracks, Medium,
            Unlock.DeathRaceWinsOnTrack("montanha"), Art(Mountain, "1º")),
        new("surfista", "SURFISTA", "FACA 800 PTS NO RELOGIO NA PRAIA", Tracks, Medium,
            Unlock.TimeAttackScoreOnTrack("praia", 800), Art(PalmTree)),
        new("patinacao_artistica", "PATINACAO ARTISTICA", "VENCA UMA CORRIDA MORTAL NA NEVE", Tracks, Medium,
            Unlock.DeathRaceWinsOnTrack("neve"), Art(Snowflake)),
        new("corredor_7", "CORREDOR 7", "VENCA NO SUPERMERCADO USANDO O CARRINHO DE MERCADO", Tracks, Medium,
            Unlock.WinWithSkinOnTrack("carrinho", "supermercado"), Skin("carrinho", "1º")),
        new("expediente", "EXPEDIENTE", "JOGUE 10 PARTIDAS NO ESCRITORIO", Tracks, Medium,
            Unlock.GamesOnTrack("escritorio", 10), Art(Computer, "10")),
        new("turista_frequente", "TURISTA FREQUENTE", "JOGUE EM 15 PISTAS DIFERENTES", Tracks, Hard,
            Unlock.TracksPlayed(15), Art(Globe, "15")),
        new("motorista_exemplar", "MOTORISTA EXEMPLAR", "TERMINE UMA PARTIDA SEM BATER EM 3 PISTAS DIFERENTES", Tracks, Hard,
            Unlock.CleanTracks(3), Art(Recolor(Shield, "BG"), "3")),
        new("cacador_de_segredos", "CACADOR DE SEGREDOS", "ENCONTRE 5 SEGREDOS ESCONDIDOS NAS PISTAS", Tracks, Hard,
            Unlock.TrackSecretsFound(5), Art(Magnifier, "5")),
        new("hat_trick", "HAT-TRICK", "VENCA 3 CORRIDAS MORTAIS NO ESTADIO", Tracks, Hard,
            Unlock.DeathRaceWinsOnTrack("estadio", 3), Art(SoccerBall, "3")),
        new("mergulhador", "MERGULHADOR", "FACA 1000 PTS NO RELOGIO NO FUNDO DO MAR", Tracks, Hard,
            Unlock.TimeAttackScoreOnTrack("fundo_do_mar", 1000), Art(Fish, "1K")),
        new("miragem", "MIRAGEM", "FACA 1000 PTS NO RELOGIO NO DESERTO", Tracks, Hard,
            Unlock.TimeAttackScoreOnTrack("deserto", 1000), Art(Cactus)),
        new("promocao_relampago", "PROMOCAO RELAMPAGO", "FACA 1000 PTS NO RELOGIO NO SUPERMERCADO", Tracks, Hard,
            Unlock.TimeAttackScoreOnTrack("supermercado", 1000), Art(Cart, "1K")),
        new("rei_do_vulcao", "REI DO VULCAO", "VENCA 3 CORRIDAS MORTAIS NO VULCAO", Tracks, Hard,
            Unlock.DeathRaceWinsOnTrack("vulcao", 3), Art(Volcano, "3")),
        new("luzes_da_cidade", "LUZES DA CIDADE", "VENCA NA CIDADE A NOITE E NA CIDADE NEON", Tracks, Hard,
            Unlock.All("VENCA NAS DUAS CIDADES", Unlock.DeathRaceWinsOnTrack("cidade_noite"), Unlock.DeathRaceWinsOnTrack("cidade_neon")), Art(NeonCity)),
        new("reciclagem", "RECICLAGEM", "VENCA NO LIXAO USANDO A CAIXA DE PAPELAO", Tracks, Hard,
            Unlock.WinWithSkinOnTrack("caixa", "lixao"), Art(TrashCan, "1º")),
        new("volta_ao_mundo", "VOLTA AO MUNDO", "VENCA A CORRIDA MORTAL EM 10 PISTAS DIFERENTES", Tracks, VeryHard,
            Unlock.TracksWon(10), Art(Globe, "10")),
        new("detetive", "DETETIVE", "ENCONTRE 10 SEGREDOS ESCONDIDOS NAS PISTAS", Tracks, VeryHard,
            Unlock.TrackSecretsFound(10), Art(Recolor(Magnifier, "CG"), "10")),
        new("motorista_de_ouro", "MOTORISTA DE OURO", "TERMINE UMA PARTIDA SEM BATER EM 10 PISTAS DIFERENTES", Tracks, VeryHard,
            Unlock.CleanTracks(10), Art(Recolor(Shield, "BY"), "10")),
        new("viajante_veloz", "VIAJANTE VELOZ", "FACA 1000 PTS NO RELOGIO EM 5 PISTAS DIFERENTES", Tracks, VeryHard,
            Unlock.ScoreOnTracks(1000, 5), Art(Recolor(Compass, "RY"), "5")),
        new("linha_de_producao", "LINHA DE PRODUCAO", "FACA 1500 PTS NO RELOGIO NA FABRICA", Tracks, VeryHard,
            Unlock.TimeAttackScoreOnTrack("fabrica", 1500), Art(Gear, "1.5K")),
        new("nas_nuvens", "NAS NUVENS", "FACA 1500 PTS NO RELOGIO ACIMA DAS NUVENS", Tracks, VeryHard,
            Unlock.TimeAttackScoreOnTrack("nuvens", 1500), Art(Cloud, "1.5K")),
        new("speedrunner", "SPEEDRUNNER", "FACA UMA VOLTA EM MENOS DE 8.4 S NO SETUP GAMER", Tracks, VeryHard,
            Unlock.LapUnderOnTrack("setup_gamer", 8.4f), Art(Keyboard)),
        new("bola_na_cacapa", "BOLA NA CACAPA", "VENCA 3 CORRIDAS MORTAIS NA MESA DE SINUCA", Tracks, VeryHard,
            Unlock.DeathRaceWinsOnTrack("sinuca", 3), Art(EightBall, "3")),
        new("doce_vitoria", "DOCE VITORIA", "VENCA NO BOLO DE ANIVERSARIO USANDO UMA COMIDA", Tracks, VeryHard,
            Unlock.WinWithCategoryOnTrack(SkinCategory.Food, "bolo"), Art(Cake, "1º")),
        new("cafe_da_manha", "CAFE DA MANHA", "VENCA NA MESA DA COZINHA USANDO A TORRADEIRA", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("torradeira", "mesa"), Skin("torradeira", "1º")),
        new("hora_do_banho", "HORA DO BANHO", "VENCA NO QUARTO DE CRIANCA USANDO O PATO", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("pato", "quarto"), Skin("pato", "1º")),
        new("peixe_fora_da_agua", "PEIXE FORA DA AGUA", "VENCA NO DESERTO USANDO O TUBARAO", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("tubarao", "deserto"), Skin("tubarao", "1º")),
        new("jurassico", "JURASSICO", "VENCA NA FLORESTA USANDO O DINOSSAURO", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("dino", "floresta"), Skin("dino", "1º")),
        new("sessao_da_tarde", "SESSAO DA TARDE", "VENCA NA SALA DE ESTAR USANDO O SOFA", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("sofa", "sala"), Skin("sofa", "1º")),
        new("montanha_russa", "MONTANHA-RUSSA", "VENCA NO PARQUE USANDO O CARRINHO DE BATE-BATE", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("bate_bate", "parque"), Skin("bate_bate", "1º")),
        new("contato_imediato", "CONTATO IMEDIATO", "VENCA NO PLANETA ALIENIGENA USANDO O OVNI", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("ovni", "alienigena"), Skin("ovni", "1º")),
        new("pequeno_passo", "UM PEQUENO PASSO", "VENCA NA ESTACAO ESPACIAL USANDO O FOGUETE", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("foguete", "espaco"), Skin("foguete", "1º")),
        new("rabisco", "RABISCO", "VENCA NO CADERNO USANDO O AVIAO DE PAPEL", Tracks, VeryHard,
            Unlock.WinWithSkinOnTrack("aviao_papel", "caderno"), Skin("aviao_papel", "1º")),
        new("overclock", "OVERCLOCK", "FACA UMA VOLTA EM MENOS DE 8.2 S NA PLACA-MAE", Tracks, Rare,
            Unlock.LapUnderOnTrack("placa_mae", 8.2f), Art(Chip)),
        new("caca_fantasmas", "CACA-FANTASMAS", "VENCA NA NOITE ASSOMBRADA USANDO O FANTASMA", Tracks, Rare,
            Unlock.WinWithSkinOnTrack("fantasma", "assombrada"), Art(Pumpkin, "1º"), IsSecret: true),
        new("passaporte_cheio", "PASSAPORTE CHEIO", "DESBLOQUEIE TODAS AS PISTAS", Tracks, Rare,
            Unlock.AllTracksUnlocked(), Art(Recolor(Globe, "GY"))),
        new("cidadao_do_mundo", "CIDADAO DO MUNDO", "JOGUE EM TODAS AS PISTAS", Tracks, Rare,
            Unlock.AllTracksPlayed(), Art(Recolor(Globe, "BC"))),
        new("dono_do_mundo", "DONO DO MUNDO", "VENCA A CORRIDA MORTAL EM TODAS AS PISTAS", Tracks, Rare,
            Unlock.AllTracksWon(), Art(Recolor(Globe, "BY", "GD"))),
        new("olho_de_aguia", "OLHO DE AGUIA", "ENCONTRE O SEGREDO DE TODAS AS PISTAS", Tracks, Rare,
            Unlock.AllTrackSecretsFound(), Art(Recolor(Magnifier, "CY", "ED"))),

        // ----- Skins -----
        new("novo_visual", "NOVO VISUAL", "DESBLOQUEIE SUA PRIMEIRA SKIN", Skins, Easy,
            Unlock.SkinsUnlocked(1), Art(PaintPalette)),
        new("quack", "QUACK!", "DESBLOQUEIE O PATO", Skins, Easy,
            Unlock.SkinEarned("pato"), Skin("pato")),
        new("troca_troca", "TROCA-TROCA", "JOGUE COM 5 SKINS DIFERENTES", Skins, Easy,
            Unlock.SkinsUsed(5), Art(Recolor(PaintPalette, "NE"), "5")),
        new("colecionador", "COLECIONADOR", "DESBLOQUEIE 5 SKINS", Skins, Medium,
            Unlock.SkinsUnlocked(5), Art(PaintPalette, "5")),
        new("colecionador_serio", "COLECIONADOR SERIO", "DESBLOQUEIE 10 SKINS", Skins, Medium,
            Unlock.SkinsUnlocked(10), Art(PaintPalette, "10")),
        new("experimentador", "EXPERIMENTADOR", "JOGUE COM 15 SKINS DIFERENTES", Skins, Medium,
            Unlock.SkinsUsed(15), Art(Recolor(PaintPalette, "NE"), "15")),
        new("batata_veloz", "BATATA VELOZ", "BATA SEU RECORDE NO RELOGIO USANDO A BATATA", Skins, Medium,
            Unlock.RecordWithSkin("batata"), Skin("batata", "REC")),
        new("garagem", "GARAGEM", "VENCA COM 3 VEICULOS DIFERENTES", Skins, Medium,
            Unlock.WinsWithCategory(SkinCategory.Vehicle, 3), Skin("padrao", "3")),
        new("obcecado", "OBCECADO", "DESBLOQUEIE 15 SKINS", Skins, Hard,
            Unlock.SkinsUnlocked(15), Art(PaintPalette, "15")),
        new("estilo_proprio", "ESTILO PROPRIO", "VENCA COM 5 SKINS DIFERENTES", Skins, Hard,
            Unlock.SkinsWonWith(5), Art(Recolor(Crown, "YF", "DP"), "5")),
        new("garagem_cheia", "GARAGEM CHEIA", "DESBLOQUEIE 25 SKINS", Skins, Hard,
            Unlock.SkinsUnlocked(25), Art(Chest, "25")),
        new("provador", "PROVADOR", "JOGUE COM 30 SKINS DIFERENTES", Skins, Hard,
            Unlock.SkinsUsed(30), Art(Recolor(PaintPalette, "NR"), "30")),
        new("fiel_escudeiro", "FIEL ESCUDEIRO", "JOGUE 50 PARTIDAS COM UMA MESMA SKIN", Skins, Hard,
            Unlock.MostGamesWithOneSkin(50), Art(Recolor(Shield, "BN"), "50")),
        new("abduzido", "ABDUZIDO", "FACA 1500 PTS NO RELOGIO USANDO O OVNI", Skins, Hard,
            Unlock.ScoreWithSkin("ovni", 1500), Skin("ovni", "1K")),
        new("galinha_dos_ovos", "GALINHA DOS OVOS DE OURO", "VENCA 5 CORRIDAS MORTAIS USANDO A GALINHA", Skins, Hard,
            Unlock.WinsWithSkin("galinha", 5), Skin("galinha", "5")),
        new("coisa_de_outro_mundo", "COISA DE OUTRO MUNDO", "VENCA A MORTAL USANDO UMA COISA ABSURDA", Skins, Hard,
            Unlock.WinsWithCategory(SkinCategory.Absurd, 1), Skin("pedra", "1º")),
        new("guarda_roupa_lotado", "GUARDA-ROUPA LOTADO", "VENCA COM 10 SKINS DIFERENTES", Skins, VeryHard,
            Unlock.SkinsWonWith(10), Art(Recolor(Crown, "YF", "DP"), "10")),
        new("ecletico", "ECLETICO", "VENCA COM UM VEICULO, UM ANIMAL, UMA COMIDA, UM OBJETO E UMA COISA ABSURDA", Skins, VeryHard,
            Unlock.CategoriesWon(5), Art(Recolor(PaintPalette, "NY"), "5")),
        new("zoologico", "ZOOLOGICO", "VENCA COM 5 ANIMAIS DIFERENTES", Skins, VeryHard,
            Unlock.WinsWithCategory(SkinCategory.Animal, 5), Skin("capivara", "5")),
        new("banquete", "BANQUETE", "VENCA COM 5 COMIDAS DIFERENTES", Skins, VeryHard,
            Unlock.WinsWithCategory(SkinCategory.Food, 5), Skin("rosquinha", "5")),
        new("ferro_velho", "FERRO-VELHO", "VENCA COM 5 OBJETOS DIFERENTES", Skins, VeryHard,
            Unlock.WinsWithCategory(SkinCategory.Thing, 5), Skin("tijolo", "5")),
        new("raiz", "RAIZ", "VENCA 10 CORRIDAS MORTAIS COM O CARRO DE CORRIDA", Skins, VeryHard,
            Unlock.WinsWithSkin("padrao", 10), Skin("padrao", "10")),
        new("descongelou", "DESCONGELOU", "VENCA NO VULCAO USANDO O CUBO DE GELO", Skins, VeryHard,
            Unlock.WinWithSkinOnTrack("cubo_gelo", "vulcao"), Skin("cubo_gelo", "1º")),
        new("museu_sobre_rodas", "MUSEU SOBRE RODAS", "DESBLOQUEIE 45 SKINS", Skins, VeryHard,
            Unlock.SkinsUnlocked(45), Art(Recolor(Chest, "YC"), "45")),
        new("horizonte_de_eventos", "HORIZONTE DE EVENTOS", "DESBLOQUEIE O BURACO NEGRO", Skins, Rare,
            Unlock.SkinEarned("buraco_negro"), Skin("buraco_negro")),
        new("colecao_secreta", "COLECAO SECRETA", "DESBLOQUEIE AS 3 SKINS SECRETAS", Skins, Rare,
            Unlock.SkinsEarned("DESBLOQUEIE AS 3 SKINS SECRETAS", "ursinho", "fantasma", "pixel"), Art(Recolor(Chest, "YP")), IsSecret: true),
        new("colecao_completa", "COLECAO COMPLETA", "DESBLOQUEIE TODAS AS SKINS", Skins, Rare,
            Unlock.AllSkins(), Skin("mascote")),

        // ----- Geral -----
        new("primeira_partida", "PRIMEIRA PARTIDA", "TERMINE SUA PRIMEIRA PARTIDA", General, Easy,
            Unlock.GamesPlayed(1), Art(Gamepad)),
        new("experimente_tudo", "EXPERIMENTE TUDO", "TERMINE UMA PARTIDA EM CADA MODO", General, Easy,
            Unlock.All("UMA PARTIDA EM CADA MODO", Unlock.DeathRaces(1), Unlock.TimeAttackRaces(1)), Art(Recolor(Gamepad, "LC"))),
        new("fregues", "FREGUES", "JOGUE 10 PARTIDAS", General, Easy,
            Unlock.GamesPlayed(10), Art(Gamepad, "10")),
        new("turbinado", "TURBINADO", "USE O TURBO POR 60 SEGUNDOS NO TOTAL", General, Easy,
            Unlock.Stat("60 S DE TURBO", p => p.TotalBoostSeconds, 60), Art(Turbo)),
        new("dia_apos_dia", "DIA APOS DIA", "JOGUE EM 3 DIAS DIFERENTES", General, Medium,
            Unlock.DaysPlayed(3), Art(Recolor(Television, "BG"), "3")),
        new("maratonista", "MARATONISTA", "PASSE 30 MINUTOS CORRENDO NO TOTAL", General, Medium,
            Unlock.Stat("30 MINUTOS CORRENDO", p => p.TotalRaceSeconds / 60f, 30), Art(Television)),
        new("volta_relampago", "VOLTA RELAMPAGO", "FACA UMA VOLTA EM MENOS DE 9 SEGUNDOS", General, Medium,
            Unlock.LapUnder(9f), Art(Lightning)),
        new("viciado_em_turbo", "VICIADO EM TURBO", "USE O TURBO POR 10 MINUTOS NO TOTAL", General, Medium,
            Unlock.Stat("10 MINUTOS DE TURBO", p => p.TotalBoostSeconds / 60f, 10), Art(Turbo, "10M")),
        new("cacador_de_conquistas", "CACADOR DE CONQUISTAS", "DESBLOQUEIE 25 CONQUISTAS", General, Medium,
            Unlock.AchievementsUnlocked(25), Art(Medal)),
        new("voce_ainda_esta_aqui", "VOCE AINDA ESTA AQUI?", "JOGUE 100 PARTIDAS", General, Medium,
            Unlock.GamesPlayed(100), Art(Gamepad, "100")),
        new("mais_rapido_que_a_luz", "MAIS RAPIDO QUE A LUZ", "FACA UMA VOLTA EM MENOS DE 8.4 SEGUNDOS", General, Hard,
            Unlock.LapUnder(8.4f), Art(Recolor(Lightning, "YC", "DB"))),
        new("mil_checkpoints", "MIL CHECKPOINTS", "PASSE POR 1000 CHECKPOINTS NO TOTAL", General, Hard,
            Unlock.Stat("1000 CHECKPOINTS", p => p.TotalCheckpoints, 1000), Art(Flag, "1K")),
        new("habito", "HABITO", "JOGUE EM 10 DIAS DIFERENTES", General, Hard,
            Unlock.DaysPlayed(10), Art(Recolor(Television, "BY"), "10")),
        new("dificil_e_bom", "DIFICIL E BOM", "DESBLOQUEIE 10 CONQUISTAS DIFICEIS", General, Hard,
            Unlock.AchievementsOfDifficulty(Difficulty.Hard, 10), Art(Recolor(Medal, "YO"), "10")),
        new("cacador_veterano", "CACADOR VETERANO", "DESBLOQUEIE 75 CONQUISTAS", General, Hard,
            Unlock.AchievementsUnlocked(75), Art(Medal, "75")),
        new("meio_caminho", "MEIO CAMINHO", "DESBLOQUEIE METADE DAS CONQUISTAS", General, VeryHard,
            Unlock.HalfOfAchievements(), Art(Medal, "50%")),
        new("de_outro_nivel", "DE OUTRO NIVEL", "DESBLOQUEIE 5 CONQUISTAS MUITO DIFICEIS", General, VeryHard,
            Unlock.AchievementsOfDifficulty(Difficulty.VeryHard, 5), Art(Recolor(Medal, "YR"), "5")),
        new("segredos_revelados", "SEGREDOS REVELADOS", "DESBLOQUEIE 10 CONQUISTAS SECRETAS", General, VeryHard,
            Unlock.SecretAchievements(10), Art(Recolor(Question, "YP"), "10")),
        new("gps_humano", "GPS HUMANO", "PASSE POR 5000 CHECKPOINTS NO TOTAL", General, VeryHard,
            Unlock.Stat("5000 CHECKPOINTS", p => p.TotalCheckpoints, 5000), Art(Recolor(Compass, "RP"), "5K")),
        new("morador_das_pistas", "MORADOR DAS PISTAS", "JOGUE 500 PARTIDAS", General, VeryHard,
            Unlock.GamesPlayed(500), Art(House)),
        new("um_mes_de_corridas", "UM MES DE CORRIDAS", "JOGUE EM 30 DIAS DIFERENTES", General, Rare,
            Unlock.DaysPlayed(30), Art(Recolor(Television, "BP"), "30")),
        new("volta_supersonica", "VOLTA SUPERSONICA", "FACA UMA VOLTA EM MENOS DE 8 SEGUNDOS", General, Rare,
            Unlock.LapUnder(8f), Art(Recolor(Lightning, "YP", "DP"))),
        new("raridade", "RARIDADE", "DESBLOQUEIE 3 CONQUISTAS RARAS", General, Rare,
            Unlock.AchievementsOfDifficulty(Difficulty.Rare, 3), Art(Recolor(Diamond, "CY", "BD"), "3")),
        new("platina", "PLATINA", "DESBLOQUEIE TODAS AS OUTRAS CONQUISTAS", General, Rare,
            Unlock.AllOtherAchievements(), Art(Recolor(Trophy, "YC", "DB", "WW"))),

        // ----- Idiotas -----
        new("isso_e_uma_galinha", "ISSO E UMA GALINHA?", "DESBLOQUEIE A GALINHA", Silly, Easy,
            Unlock.SkinEarned("galinha"), Skin("galinha")),
        new(WhereAreTheBrakesId, "ONDE ESTAO OS FREIOS?", "BATA 10 VEZES NUMA MESMA PARTIDA", Silly, Easy,
            Unlock.Stat("10 BATIDAS NUMA PARTIDA", p => p.MostCollisionsInOneRace, 10), Art(Explosion)),
        new("eu_nao_queria_fazer_isso", "EU NAO QUERIA FAZER ISSO", "BATA NUM RIVAL LOGO NA LARGADA", Silly, Easy,
            Unlock.Stat("BATIDA NA LARGADA", p => p.StartLineCrashes, 1), Art(Oops)),
        new("turbo_pra_lugar_nenhum", "TURBO PRA LUGAR NENHUM", "SEJA ELIMINADO COM O TURBO LIGADO", Silly, Easy,
            Unlock.Stat("ELIMINADO NO TURBO", p => p.EliminatedWhileBoosting, 1), Art(Recolor(Turbo, "CR"))),
        new("pausa_pro_lanche", "PAUSA PRO LANCHE", "PAUSE O JOGO 10 VEZES", Silly, Easy,
            Unlock.Stat("10 PAUSAS", p => p.TotalPauses, 10), Art(Pause)),
        new("mas_eu_quero", "MAS EU QUERO!", "TENTE EQUIPAR ALGO BLOQUEADO 10 VEZES", Silly, Easy,
            Unlock.Stat("10 TENTATIVAS", p => p.DeniedEquips, 10), Art(Recolor(Chest, "YE", "DK"))),
        new("eu_tinha_um_plano", "EU TINHA UM PLANO", "SEJA O PRIMEIRO ELIMINADO DA CORRIDA MORTAL", Silly, Easy,
            Unlock.Stat("PRIMEIRO ELIMINADO", p => p.EliminationFirstOuts, 1), Art(Bomb), IsSecret: true),
        new("parado_no_transito", "PARADO NO TRANSITO", "FIQUE 10 SEGUNDOS PARADO NUMA PARTIDA", Silly, Easy,
            Unlock.Stat("10 S PARADO", p => p.LongestStandstillSeconds, 10), Art(Cone), IsSecret: true),
        new("isso_foi_de_proposito", "ISSO FOI DE PROPOSITO?", "ANDE DE RE POR 5 SEGUNDOS SEGUIDOS", Silly, Easy,
            Unlock.Stat("5 S DE RE", p => p.LongestReverseSeconds, 5), Art(Reverse), IsSecret: true),
        new("ta_pausando_por_que", "TA PAUSANDO POR QUE?", "PAUSE 5 VEZES NUMA MESMA PARTIDA", Silly, Easy,
            Unlock.Stat("5 PAUSAS NUMA PARTIDA", p => p.MostPausesInOneRace, 5), Art(Recolor(Pause, "WR")), IsSecret: true),
        new(WasThatSupposedToHappenId, "ERA PARA ISSO ACONTECER?", "TERMINE O CONTRA O RELOGIO COM 0 PONTOS", Silly, Easy,
            Unlock.Stat("0 PONTOS", p => p.TimeAttackZeroScores, 1), Art(Bug), IsSecret: true),
        new("cocorico", "COCORICO!", "CUTUQUE A GALINHA DO MENU ATE ELA RECLAMAR", Silly, Easy,
            Unlock.Discovered(Discovery.Cocorico, "CUTUQUE A GALINHA DO MENU"), Skin("mascote"), IsSecret: true),
        new("so_olhando", "SO OLHANDO", "FIQUE 2 MINUTOS NO MENU SEM MEXER EM NADA", Silly, Easy,
            Unlock.Discovered(Discovery.MenuIdle, "FIQUE PARADO NO MENU"), Art(Sleep), IsSecret: true),
        new("quase", "QUASE!", "CAIA NA ULTIMA ELIMINACAO DA CORRIDA MORTAL", Silly, Medium,
            Unlock.Stat("2º LUGAR NA MORTAL", p => p.EliminationRunnerUps, 1), Art(BrokenHeart)),
        new("eu_sabia", "EU SABIA", "CAIA NA ULTIMA ELIMINACAO DA CORRIDA MORTAL 5 VEZES", Silly, Medium,
            Unlock.Stat("5 VEZES EM 2º", p => p.EliminationRunnerUps, 5), Art(BrokenHeart, "5")),
        new("piloto_profissional", "PILOTO PROFISSIONAL", "BATA 20 VEZES NUMA MESMA PARTIDA", Silly, Medium,
            Unlock.Stat("20 BATIDAS NUMA PARTIDA", p => p.MostCollisionsInOneRace, 20), Art(Recolor(Explosion, "YR"), "20")),
        new("isso_foi_necessario", "ISSO FOI NECESSARIO?", "ANDE DE RE POR 15 SEGUNDOS SEGUIDOS", Silly, Medium,
            Unlock.Stat("15 S DE RE", p => p.LongestReverseSeconds, 15), Art(Reverse, "15")),
        new("contramao", "CONTRAMAO", "ANDE 10 SEGUNDOS SEGUIDOS NA CONTRAMAO", Silly, Medium,
            Unlock.Stat("10 S NA CONTRAMAO", p => p.LongestWrongWaySeconds, 10), Art(Recolor(Reverse, "RY"), "10")),
        new("estatua", "ESTATUA", "FIQUE 15 SEGUNDOS PARADO NUMA PARTIDA", Silly, Medium,
            Unlock.Standstill(15), Skin("pedra")),
        new("indeciso", "INDECISO", "TROQUE DE SKIN 30 VEZES", Silly, Medium,
            Unlock.Stat("30 TROCAS DE SKIN", p => p.SkinChanges, 30), Art(Recolor(PaintPalette, "RB"), "30")),
        new("ima_de_obstaculos", "IMA DE OBSTACULOS", "BATA 20 VEZES NOS OBSTACULOS DO RELOGIO", Silly, Medium,
            Unlock.Stat("20 BATIDAS EM OBSTACULOS", p => p.TimeAttackHazardHits, 20), Skin("obstaculo", "20")),
        new("eu_tenho_um_talento", "EU TENHO UM TALENTO", "SEJA O PRIMEIRO ELIMINADO 10 VEZES", Silly, Medium,
            Unlock.Stat("10 VEZES O PRIMEIRO A CAIR", p => p.EliminationFirstOuts, 10), Art(Bomb, "10")),
        new("nao_era_pra_isso", "NAO ERA PRA ISSO", "JOGUE NO VULCAO USANDO O CUBO DE GELO", Silly, Medium,
            Unlock.PlayedWithSkinOnTrack("cubo_gelo", "vulcao"), Skin("cubo_gelo")),
        new("o_que_voce_faz_aqui", "O QUE VOCE ESTA FAZENDO AQUI?", "JOGUE NA ESTACAO ESPACIAL USANDO A GALINHA", Silly, Medium,
            Unlock.PlayedWithSkinOnTrack("galinha", "espaco"), Skin("galinha", "?")),
        new("quack_quack", "QUACK", "VENCA UMA CORRIDA MORTAL USANDO O PATO", Silly, Medium,
            Unlock.WinsWithSkin("pato"), Skin("pato", "1º")),
        new("problema_seu", "PROBLEMA SEU", "VENCA UMA CORRIDA MORTAL USANDO O JACARE", Silly, Medium,
            Unlock.WinsWithSkin("jacare"), Skin("jacare", "1º")),
        new("fazendinha", "FAZENDINHA", "VENCA COM A GALINHA E TAMBEM COM O PATO", Silly, Medium,
            Unlock.WonWithEachSkin("VENCA COM GALINHA E PATO", "galinha", "pato"), Skin("galinha", "1º")),
        new("cade_o_tempo", "CADE O TEMPO?", "PERCA 10 S EM BATIDAS NUMA PARTIDA DO RELOGIO", Silly, Medium,
            Unlock.Stat("10 S PERDIDOS EM BATIDAS", p => p.MostTimeLostInOneRun, 10), Art(Recolor(Stopwatch, "RE", "EK"), "-10")),
        new("colecionador_de_amassados", "COLECIONADOR DE AMASSADOS", "BATA 200 VEZES NO TOTAL", Silly, Medium,
            Unlock.Stat("200 BATIDAS", p => p.TotalCollisions, 200), Art(Wrench, "200")),
        new("eu_tenho_tempo", "EU TENHO TEMPO!", "PASSE NUM CHECKPOINT COM MENOS DE 1 S NO RELOGIO", Silly, Medium,
            Unlock.Stat("CHECKPOINT NO ULTIMO SEGUNDO", p => p.TimeAttackClutchCheckpoints, 1), Art(Recolor(Stopwatch, "ER", "WY")), IsSecret: true),
        new("silencio_no_set", "SILENCIO NO SET", "TERMINE UMA PARTIDA COM MUSICA E EFEITOS NO MUDO", Silly, Medium,
            Unlock.Stat("PARTIDA NO MUDO", p => p.SilentGames, 1), Art(Mute), IsSecret: true),
        new("coruja", "CORUJA", "TERMINE UMA PARTIDA DE MADRUGADA (ENTRE 0H E 5H)", Silly, Medium,
            Unlock.Stat("PARTIDA DE MADRUGADA", p => p.NightOwlGames, 1), Art(Recolor(Sleep, "WY")), IsSecret: true),
        new("o_carro_esta_bem", "O CARRO ESTA BEM?", "VENCA UMA CORRIDA MORTAL BATENDO 10 VEZES OU MAIS", Silly, Hard,
            Unlock.Stat("VENCA COM 10 BATIDAS", p => p.MostCollisionsInAWin, 10), Art(Recolor(Wrench, "LR"), "10")),
        new("moonwalk", "MOONWALK", "PASSE POR 10 CHECKPOINTS ANDANDO DE RE", Silly, Hard,
            Unlock.Stat("10 CHECKPOINTS DE RE", p => p.ReverseCheckpoints, 10), Art(Recolor(Reverse, "WP"), "10")),
        new("por_que", "POR QUE?", "DESBLOQUEIE O VASO SANITARIO", Silly, Hard,
            Unlock.SkinEarned("privada"), Skin("privada")),
        new("sedentario", "SEDENTARIO", "VENCA UMA CORRIDA MORTAL USANDO O SOFA", Silly, Hard,
            Unlock.WinsWithSkin("sofa"), Skin("sofa", "1º")),
        new("demolidor", "DEMOLIDOR", "BATA 1000 VEZES NO TOTAL", Silly, Hard,
            Unlock.Stat("1000 BATIDAS", p => p.TotalCollisions, 1000), Art(Recolor(Explosion, "OR", "YO"), "1K")),
        new("decisao_questionavel", "DECISAO QUESTIONAVEL", "VENCA UMA CORRIDA MORTAL USANDO O VASO SANITARIO", Silly, Hard,
            Unlock.WinsWithSkin("privada"), Skin("privada", "1º"), IsSecret: true),
        new("nao_somos_mais_os_unicos", "NAO SOMOS MAIS OS UNICOS", "DESBLOQUEIE O OVNI", Silly, Hard,
            Unlock.SkinEarned("ovni"), Skin("ovni"), IsSecret: true),
        new("meu_deus", "MEU DEUS", "VENCA UMA CORRIDA MORTAL BATENDO 20 VEZES OU MAIS", Silly, VeryHard,
            Unlock.Stat("VENCA COM 20 BATIDAS", p => p.MostCollisionsInAWin, 20), Art(Recolor(Wrench, "LP"), "20")),
        new("so_viro_pra_esquerda", "SO SEI VIRAR PRA ESQUERDA", "VENCA A MORTAL SEM VIRAR PRA DIREITA NENHUMA VEZ", Silly, VeryHard,
            Unlock.Stat("VENCA SEM VIRAR PRA DIREITA", p => p.EliminationLeftOnlyWins, 1), Art(Recolor(ArrowUp, "GB", "gb"))),
        new("dieta_balanceada", "DIETA BALANCEADA", "VENCA COM A BANANA, A BATATA, A PIZZA E A MELANCIA", Silly, VeryHard,
            Unlock.WonWithEachSkin("VENCA COM AS 4 COMIDAS", "banana", "batata", "pizza", "melancia"), Skin("pizza", "4")),
        new("insonia", "INSONIA", "TERMINE 10 PARTIDAS DE MADRUGADA", Silly, VeryHard,
            Unlock.Stat("10 PARTIDAS DE MADRUGADA", p => p.NightOwlGames, 10), Art(Recolor(Sleep, "WP"), "10"), IsSecret: true),
        new("isso_conta_como_estrategia", "ISSO CONTA COMO ESTRATEGIA?", "VENCA A MORTAL PARADO OU DE RE NA ULTIMA ELIMINACAO", Silly, Rare,
            Unlock.Stat("VITORIA PARADO", p => p.EliminationLazyWins, 1), Art(Sleep), IsSecret: true),
        new("o_codigo", "O CODIGO", "DIGITE O CODIGO SECRETO NO MENU PRINCIPAL", Silly, Rare,
            Unlock.Discovered(Discovery.Konami, "DIGITE O CODIGO SECRETO"), Art(Invader), IsSecret: true),
        new("estava_em_casa", "ESTAVA EM CASA", "VENCA NO MUNDO 8 BITS USANDO O PIXEL PERDIDO", Silly, Rare,
            Unlock.WinWithSkinOnTrack("pixel", "retro"), Skin("pixel", "1º"), IsSecret: true),
    ];

    public static IReadOnlyList<Achievement> All { get; } = [.. Handmade, .. TrackThemes.All.Select(TrackSecretAchievement)];

    /// <summary>A conquista secreta de uma pista: achar o detalhe escondido nela.</summary>
    public static string TrackSecretId(TrackTheme track) => $"segredo_{track.Id}";

    /// <summary>Achar o segredo de uma pista difícil de liberar também conta como feito mais difícil.</summary>
    private static Achievement TrackSecretAchievement(TrackTheme track) => new(
        TrackSecretId(track),
        track.SecretName,
        track.SecretDescription,
        Tracks,
        track.Difficulty switch
        {
            Difficulty.Hard => Hard,
            Difficulty.VeryHard or Difficulty.Rare => VeryHard,
            _ => Medium,
        },
        Unlock.TrackSecretFound(track.Id),
        Art(track.Icon, "?"),
        IsSecret: true);

    private static Dictionary<string, Achievement> _byId;

    private static Dictionary<string, Achievement> ById => _byId ??= All.ToDictionary(achievement => achievement.Id);

    public static Achievement Find(string id) => id is not null && ById.TryGetValue(id, out Achievement achievement) ? achievement : null;

    public static bool IsUnlocked(Achievement achievement, SaveData progress) =>
        progress.UnlockedAchievementIds.Contains(achievement.Id);

    /// <summary>Quantas conquistas (que existem de verdade no catálogo) já foram liberadas.</summary>
    public static int UnlockedCount(SaveData progress) => progress.UnlockedAchievementIds.Distinct().Count(id => ById.ContainsKey(id));
}
